### ISSUE TITLE
MP3 streams not working

### ISSUE THREAD

**Issue by fbreitwieser** [billthefarmer/shorty#1]
Hello, thank you for this project. I'm looking forward to replacing Tunein Radio, finally. I tried adding a few streams, however none of them worked. Here they are:

Radio Oe1: http://mp3stream3.apasf.apa.at:8000/listen.pls
Radio Wien: http://mp3stream2.apasf.apa.at:8000/listen.pls
FM4: http://mp3stream1.apasf.apa.at:8000/listen.pls
WEAA: http://amber.streamguys.com:4020/live
WYPR: http://live.str3am.com:2410/wypr.m3u

Using Tasker, they do work.

**Comment by billthefarmer** [comment]
Florian
You must put the name of the station in the first field and the URL in the second field. There are prompts. I have tested all of your URLs and they all work fine.
Regards
Bill
On 21 May 2015 19:15, Florian Breitwieser notifications@github.com wrote:Hello, thank you for this project. I'm looking forward to replacing Tunein Radio, finally. I tried adding a few streams, however none of them worked. Here they are:

Radio Oe1: http://mp3stream3.apasf.apa.at:8000/listen.pls
Radio Wien: http://mp3stream2.apasf.apa.at:8000/listen.pls
FM4: http://mp3stream1.apasf.apa.at:8000/listen.pls
WEAA: http://amber.streamguys.com:4020/live
WYPR: http://live.str3am.com:2410/wypr.m3u

Using Tasker, they do work.

**Comment by fbreitwieser** [comment]
Hi Bill, indeed it works also for me now. I did enter it that way before - it seems my network is funny today. Thanks for the prompt answer!

**Comment by sebus1201** [comment]
Hello. Your project Shorty is great. But I have one problem. On my LG E430 (screen resolution 320x240) I can’t scroll list of station on playlist screen, it's only display three positions, but I added almost 19 entires. Please, can You fix it ? Thanks in advance. 
PS. Sorry for my bad English.

**Comment by billthefarmer** [comment]
I have released a new version with updated layout for the lookup screen. It should appear on F-Droid within a day or so. I tested it on the emulator with a 320x240 screen running 4.1.2, which is what LG says your phone runs and it works fine. However I don't have a lot of confidence in the Android emulators.
