### ISSUE TITLE
Data loss while using the app (the fragment disappear after double screen rotation)

### ISSUE THREAD

**Issue by davirec** [billthefarmer/shorty#10]
When I perform these sequences of events, the fragment disappears after double screen rotation:

1. Go to the main activity
2. Tap in the hamburger menu
3. Tap in Import menu
4. A screen similar to this will appear:

Before rotation:

<img src="https://user-images.githubusercontent.com/3637419/158042739-14299e34-7784-45a4-9d72-8e0abefc067f.png" width=30% height=30%>

5. Force the pause from the activity and then return to the activity (double screen rotation). Note that the fragment disappears. 

The expected behavior is the return to the state of the previous image.

However, the fragment disappears.

After rotation:

<img src="https://user-images.githubusercontent.com/3637419/158042749-3c8ed4d2-db86-43e1-9536-3f8dbef1bf49.png" width=30% height=30%>

Note: 
- The pause from activity(1) can be performed in several ways. We suggest using a double screen rotation (starts in portrait, goes to landscape, and back to portrait) with this function previously enabled in the smartphone.
- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

Device:
- Device: Moto G30 with OS: Android 11
- Version: 1.15
- Device language: English

1. https://developer.android.com/guide/components/activities/activity-lifecycle

**Comment by billthefarmer** [comment]
It's an alert dialog and they do that. There isn't anything a developer can do about it apart from not use them. Why rotate the device half way through importing a file? I didn't think anyone was still using this app.

**Comment by davirec** [comment]
Hi billthefarmer, 
I'm working with apps hosted on F-droid to check for data loss after double screen rotation for a software engineering experiment. This app was selected following my search criteria. We use double screen rotation to execute an event to force the activity to be destroyed. It is run twice to reach a state that should be the same as the screen before if no data loss occurred.

We found failures similar in the activities:

- MainActivity: shorty fragment disappears, the menu disappears, the pop-up menu disappears.


<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159200980-42e7fa5a-3dda-43fc-986a-4dadf132aed6.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159200976-b67c8297-4b6a-47c8-bd7c-0db13128fc64.png" width=20% height=20%>
</figure>

</div> 



<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159201008-e1ee6eac-5289-4488-9004-fa3df33d2632.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159201006-d45965e2-b631-42b2-a048-a5d8ce66e2a6.png" width=20% height=20%>
</figure>

</div> 
 





- LookupActivity: menu disappears, the lost focus of element, lost focus of the second element.

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159200829-6cdf7378-356d-40fd-a4c3-5d5794b1bb00.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159200835-b67b3491-1125-480f-bbfb-fe1efa4d687d.png" width=20% height=20%>
</figure>

</div> 


<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159200877-f89afbbd-c684-4a4d-b4da-6695f50df9fb.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159200874-8fc0a1ad-1ec7-4b99-b6e8-7ef16b818fbc.png" width=20% height=20%>
</figure>

</div> 


<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159200940-db3128fc-8abb-4ca1-b09c-db678dacd961.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159200938-c70a2337-02cd-460e-8e4a-bb5c78d23107.png" width=20% height=20%>
</figure>

</div>

**Comment by billthefarmer** [comment]
1. Perhaps you should read the comments above. 'It's an alert dialog and they do that.' If you feel so strongly about it, perhaps you should take it up with Google.
2. Can't reproduce it.
3. ?
4. ?

When users raise issues I look at their profile to see what, if anything, is there. You seem to spend your days raising spurious rotation issues on random apps. You may think that is a worthwhile activity, I've got more important things to worry about.

**Comment by davirec** [comment]
Hi @billthefarmer ! Sorry about that :)
I'm working with apps hosted on F-droid to check for data loss after double screen rotation for a software engineering experiment.
