### ISSUE TITLE
A confusing widget on "Shorty" 's UI

### ISSUE THREAD

**Issue by b450mhdv** [billthefarmer/shorty#11]
Hello @billthefarmer  , I enjoy using this app, it is very useful for me! However, I found a misleading widget in this app.
I inadvertently clicked the "Cancel" button, which caused the direct shutdown of this app. This confuses me because I don't think that clicking a "cancel" button can cause the closing of the app. This might be a misleading widget, and users like me might be confused when they touch the "cancel" for the first time.
So, just as a personal suggestion, could you try to redesign the widget? And thanks for your useful app!
<img src="https://user-images.githubusercontent.com/78015408/167302487-e9ddbbb6-01aa-4514-b23c-ea29d2a848c9.jpg" width="300px"/>

**Comment by billthefarmer** [comment]
This app's primary purpose is to create shortcuts. If the user decides not to do that and cancels or touches the back button the app closes. There's not much else it could do. That is also explained in the help.

**Comment by billthefarmer** [comment]
This app's primary purpose is to create shortcuts. If the user decides not to do that and cancels or touches the back button the app closes. There's not much else it could do. That is also explained in the help.
