### ISSUE TITLE
Scrollable view changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [billthefarmer/shorty#3]
When I perform this sequence of events, the scrollable view on screen goes back to the top:

1. Click on Help Icon
2. Scroll Down
3. Orientation Change

**Comment by billthefarmer** [comment]
See https://github.com/billthefarmer/currency/issues/9 comment on [ScrollView](https://developer.android.com/reference/android/widget/ScrollView.html#onSaveInstanceState()).

**Comment by reverse-unina** [comment]
Yes, you are right!
Do you think that getScrollY and setScrollY could work?

https://developer.android.com/reference/android/view/View.html#getScrollY%28%29

**Comment by reverse-unina** [comment]
I am looking for an answer online and I found this discussion interesting:

http://stackoverflow.com/questions/6438061/can-i-scroll-a-scrollview-programmatically-in-android

**Comment by billthefarmer** [comment]
It appears to be by design that this doesn't work - [ScrollView.onSaveInstanceState()](http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.4.4_r1/android/widget/ScrollView.java#ScrollView.onSaveInstanceState%28%29).

**Comment by reverse-unina** [comment]
Interesting! What if:
mContext.getApplicationInfo().targetSdkVersion > Build.VERSION_CODES.JELLY_BEAN_MR2?

**Comment by billthefarmer** [comment]
That would appear to be it. If I increase the targetSdkVersion, the scroll position is preserved.

**Comment by reverse-unina** [comment]
It seems that increasing the targetSdkVersion is not enough to solve this problem. 
I tried to add an id in the scrollView element in help.xml and now it works for me.

**Comment by billthefarmer** [comment]
Yes, I tried that first, as per the docs, but it didn't work until I checked the sources and updated the sdk version.
