### ISSUE TITLE
AAC and M3U8 streams do not play 

### ISSUE THREAD

**Issue by b4198eb1aa** [billthefarmer/shorty#5]
Shorty uses Intent Radio and Intent Radio uses the Android default player which will not stream bandwidth conserving AAC streams, or the newer more fault tolerant M3U8 streams. 

It would be awesome if there were a verson, or a configuration setting within Shorty to use the open source VLC player (or a similar alternative) which does stream these newer stream formats. 

Note that Shorty default station, BBC Radio 4 also now has an M3U8 stream. It streams with this M3U8 file http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/llnw/bbc_radio_fourfm.m3u8  which I believe, in turn uses the AAC format.

**Comment by billthefarmer** [comment]
I haven't looked at this app for a long time, I didn't think there were many users. If there are other players that will run in the background after receiving an Intent with a stream URL, I agree, it would be a good idea.

**Comment by b4198eb1aa** [comment]
Here is the list of Android intents for the free open source VLC player https://wiki.videolan.org/Android_Player_Intents/  and the player's home page says " VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files, and various streaming protocols."  ( https://www.videolan.org/vlc/ ) 

I think many people don't know how to find the URLs to the stations they like. One of the best easy to use sources is the CSV delimited file (spreadsheet) that is updated daily: http://www.radiosure.com/rsdbms/stations2.zip 

Even with that spreadheet, I had difficulty separating the AAC streams from the MP3 streams - many would not stream because the Android default player does not support them.   I suspect that is a deterrent to the non-technical user. 

If there were several different station lists that users could  download and import as a starting point, I think we will see a lot of new users.  Perhaps a list of classical music streams, rock music streams, etc so that people don't have to be technical to enjoy the wonderful Shorty.  I'd be willing to put together a few such CSV files for shorty but I don't know enough about github to upload them so others can download.
