### ISSUE TITLE
Android's ExoPlayer supports AAC M3U8 URL streams 

### ISSUE THREAD

**Issue by b4198eb1aa** [billthefarmer/shorty#8]
Please consider a version of Shorty that uses the Android ExoPlayer. I understand that it used by most (all?) podcast apps on Android. It definitely streams the newer AAC and M3U8 files.  Here is some info:

https://www.raywenderlich.com/5573-media-playback-on-android-with-exoplayer-getting-started

https://github.com/google/ExoPlayer/issues/4782

Love the app. I do use it with VLC when stationary to stream these types of URLs but not when driving in the car - the VLC does not have intents to indicate lost internet connection and the allow the automatic restart of a stream - both are required to listen to a stream while driving and passing from cell tower to cell tower and sometimes losing connectivity.  I am not sure whether ExoPlayer does, I don't understand the technology very well.

FWIW - I use Shorty in conjunction with Intent Radio to enable the automatic restarts. 
https://play.google.com/store/apps/details?id=org.smblott.intentradioio&hl=en_US

**Comment by billthefarmer** [comment]
I wrote this app originally as a front end for Intent Radio because there didn't appear to be a free one at the time. Someone suggested that I extend it to use VLC, which I did. However there doesn't appear to be a ExoPlayer app, it's a library.
