### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [billthefarmer/shorty#9]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by billthefarmer** [comment]
Yes I've done that for most of my other apps. I'm not sure how many actually use this one, based on the low number of issues after 6 years.

**Comment by mondlicht-und-sterne** [comment]
if this is not for you, you can also close the issue. i "only" go through the apps that do not have screenshots. 

then the view in fdroid would simply look nicer.
